<?php

declare(strict_types=1);

namespace Arqel\Core\Generators;

use Illuminate\Support\Str;
use InvalidArgumentException;

/**
 * Pure code-generator for the interactive `arqel:resource` flow
 * (CLI-TUI-002). Produces PHP source strings only — never touches
 * the filesystem. The Console command decides where to write.
 *
 * @phpstan-type FieldDescriptor array{name: string, type: string, related?: ?string}
 */
final readonly class ResourceGenerator
{
    public const array SUPPORTED_TEST_FRAMEWORKS = ['pest', 'none'];

    /**
     * @param list<FieldDescriptor> $fields
     */
    public function __construct(
        public string $modelClass,
        public string $label,
        public ?string $group,
        public ?string $icon,
        public array $fields,
        public bool $withPolicy,
        public bool $withFormRequests,
        public ?string $testFramework,
        public string $resourceNamespace = 'App\\Arqel\\Resources',
    ) {
        if ($modelClass === '') {
            throw new InvalidArgumentException('Model class cannot be empty.');
        }

        if ($testFramework !== null && ! in_array($testFramework, self::SUPPORTED_TEST_FRAMEWORKS, true)) {
            throw new InvalidArgumentException(
                "Unsupported test framework [{$testFramework}]. Supported: pest, none.",
            );
        }
    }

    public function modelBasename(): string
    {
        return class_basename($this->modelClass);
    }

    public function resourceClass(): string
    {
        return $this->modelBasename().'Resource';
    }

    public function policyClass(): string
    {
        return $this->modelBasename().'Policy';
    }

    public function generateResourceFile(): string
    {
        $modelClass = ltrim($this->modelClass, '\\');
        $modelBasename = $this->modelBasename();
        $resourceClass = $this->resourceClass();
        $namespace = rtrim($this->resourceNamespace, '\\');

        $fieldsBody = $this->renderFieldsBody();

        $labelLine = $this->label !== ''
            ? "    public static ?string \$label = '".$this->escapeSingle($this->label)."';"
            : null;
        $groupLine = $this->group !== null && $this->group !== ''
            ? "    public static ?string \$navigationGroup = '".$this->escapeSingle($this->group)."';"
            : null;
        $iconLine = $this->icon !== null && $this->icon !== ''
            ? "    public static ?string \$navigationIcon = '".$this->escapeSingle($this->icon)."';"
            : null;

        $metadataLines = array_filter([$labelLine, $groupLine, $iconLine], fn ($l) => $l !== null);
        $metadataBlock = $metadataLines === []
            ? ''
            : "\n".implode("\n", $metadataLines)."\n";

        return <<<PHP
<?php

declare(strict_types=1);

namespace {$namespace};

use {$modelClass};
use Arqel\\Core\\Resources\\Resource;

/**
 * Auto-generated by `arqel:resource` (interactive mode — CLI-TUI-002).
 */
final class {$resourceClass} extends Resource
{
    public static string \$model = {$modelBasename}::class;
{$metadataBlock}
    public function fields(): array
    {
        return [
{$fieldsBody}
        ];
    }
}
PHP;
    }

    public function generatePolicyFile(): string
    {
        $modelClass = ltrim($this->modelClass, '\\');
        $modelBasename = $this->modelBasename();
        $policyClass = $this->policyClass();
        $variable = Str::camel($modelBasename);

        return <<<PHP
<?php

declare(strict_types=1);

namespace App\\Policies;

use {$modelClass};
use Illuminate\\Foundation\\Auth\\User;

/**
 * Auto-generated by `arqel:resource` (interactive mode).
 *
 * Defaults to ALLOW everywhere so the Resource works out of the box.
 * Tighten each method as your authorization rules harden.
 */
final class {$policyClass}
{
    public function viewAny(User \$user): bool
    {
        return true;
    }

    public function view(User \$user, {$modelBasename} \${$variable}): bool
    {
        return true;
    }

    public function create(User \$user): bool
    {
        return true;
    }

    public function update(User \$user, {$modelBasename} \${$variable}): bool
    {
        return true;
    }

    public function delete(User \$user, {$modelBasename} \${$variable}): bool
    {
        return true;
    }
}
PHP;
    }

    public function generateRequestFile(string $kind): string
    {
        if ($kind !== 'store' && $kind !== 'update') {
            throw new InvalidArgumentException("Unsupported request kind [{$kind}].");
        }

        $modelBasename = $this->modelBasename();
        $prefix = $kind === 'store' ? 'Store' : 'Update';
        $className = $prefix.$modelBasename.'Request';

        return <<<PHP
<?php

declare(strict_types=1);

namespace App\\Http\\Requests;

use Illuminate\\Foundation\\Http\\FormRequest;

/**
 * Auto-generated by `arqel:resource` (interactive mode).
 */
final class {$className} extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        // TODO: declare validation rules. By default Arqel reads
        // rules from Resource::fields() — only override here when
        // you need request-specific rules outside the field schema.
        return [];
    }
}
PHP;
    }

    public function generateTestFile(): string
    {
        $modelBasename = $this->modelBasename();
        $resourceClass = $this->resourceClass();
        $namespace = rtrim($this->resourceNamespace, '\\');

        return <<<PHP
<?php

declare(strict_types=1);

use {$namespace}\\{$resourceClass};

it('registers the {$modelBasename} resource class', function (): void {
    expect(class_exists({$resourceClass}::class))->toBeTrue();
});
PHP;
    }

    private function renderFieldsBody(): string
    {
        if ($this->fields === []) {
            return "            // Field::text('name')->required(),";
        }

        $lines = [];
        foreach ($this->fields as $field) {
            $name = $field['name'];
            $type = $field['type'];
            if ($name === '') {
                continue;
            }
            $escaped = $this->escapeSingle($name);
            $lines[] = "            Field::{$type}('{$escaped}'),";
        }

        return $lines === []
            ? "            // Field::text('name')->required(),"
            : implode("\n", $lines);
    }

    private function escapeSingle(string $value): string
    {
        return str_replace(['\\', "'"], ['\\\\', "\\'"], $value);
    }
}
